HW06 done
AlGuran/otus_home_work pull request #7
Opened 2021-04-23 19:19 UTC by AlGuran

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-04-26 16:50 UTC, kulti requested changes
Ярослав, есть один момент в логике кода, над которым нужно подумать. По моему при записи в bufferChannel там могут быть проблемы.

Также будет здорово подумать еще над тестами. Самое простое — подумать на входными данными, какие значения они могут принимать (максимальные, минимальные, валидные, невалидные).

2021-04-26 16:50 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		}(stage(out), done)
done можно не передавать отдельно. Он и через замыкание отлично попадет внутрь.

2021-04-26 16:50 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +						bufferChannel <- v
Может ли так произойти, что здесь в момента записи читателя(ей) этого канала уже не будет? Если да, то горутина зависнет навсегда.

2021-04-26 16:50 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +			}(bufferChannel)
Здесь тоже можно явно не передавать.

2021-04-26 16:50 UTC, kulti commented on hw06_pipeline_execution/pipeline_test.go
> +		abortDur := sleepPerStage*19 + fault
Не похоже, что тут 200 ms.

Сам тест довольно сомнительной полезности. Не понимаю, что интересного или важного он проверяет.

2021-04-26 16:50 UTC, kulti commented on hw06_pipeline_execution/pipeline_test.go
> +	t.Run("empty data", func(t *testing.T) {
Необходимость этого теста тоже вызывает у меня сомнения. Читаю его так — если закрыть in, то out тоже закроется. Самый первый тест уже это проверяет и дополнительно еще и данные через канал прогоняет.

2021-05-02 22:59 UTC, AlGuran commented on hw06_pipeline_execution/pipeline_test.go
> +		abortDur := sleepPerStage*19 + fault
По идее этот тест должен был проверять что даже если done есть то все отработает в нужное время прежде, чем передастся сигнал на закрытие, но по здравом размышлении я понял, что в целом это покрывается проверкой времени выполнения пайплайнов в первом тесте

2021-05-02 23:00 UTC, AlGuran commented on hw06_pipeline_execution/pipeline_test.go
> +	t.Run("empty data", func(t *testing.T) {
Этот тест проверяет, что даже при пустом закрытом in программа не выдаст ошибку и не зависнет с попыткой записи

2021-05-02 23:02 UTC, AlGuran commented on hw06_pipeline_execution/pipeline.go
> +						bufferChannel <- v
Было два варианта обезопасить себя от этого, решение сделать канал буферизированным мне показалось более читабельным, чем вставлять еще один селект

2021-05-07 05:32 UTC, kulti commented on hw06_pipeline_execution/pipeline_test.go
> +	t.Run("empty data", func(t *testing.T) {
Так первый тест заканчивается именно пустым закрытым каналом. Сначала в канале есть данные, потом их вычитывают и они заканчиваются. В этом тесте нет ничего нового.

2021-05-07 05:32 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +						bufferChannel <- v
Может ли зависнуть запись в буферезованный канал? Если считаете, что нет, то надо повторить эту тему.

Если считаете, что да, то сразу возникают вопросы:
- В каких случаях?
- Гарантируется ли, что в этом коде эти случаи не произойдут?

Я не вижу таких гарантий. Возможно, они есть, но они неочевидны. Так что по читаемости текущий вариант точно проигрывает селекту. Селект с двумя кейзами done и запись дает гарантию, что он будет ждать, пока не закроют done или пока не будет готов читатеть — все очевидно.

2021-12-02 11:25 UTC, kulti approved these changes
ДЗ принято — 9/10.

В рамках ДЗ решение рабочее. Есть один нюанс из-за которого часть горутин может зависнуть навсегда. Рекомендую посмотреть разбор этого ДЗ (было на специальном занятии, плюс к тому же занятию прикреплено отдельное видео с разбором этого ДЗ).

2021-12-02 11:25 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		}(stage(out))
Такие длинные анонимные функции плохо читаются. А уже если они принимаю параметры, то совсем мрак :) Рекомендую их писать отдельно.

2021-12-08 22:01 UTC, merged